@extends('admin.layout')
@section('title', 'Xử lý hoàn hàng')
@section('page-title', 'Phiếu ' . $returnRequest->return_code)
@section('content')
@php($labels = \App\Models\ReturnRequest::STATUS_LABELS)
<div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]">
<div class="space-y-5">
    <section class="rounded-2xl border border-white/5 bg-night-soft p-5"><div class="flex flex-wrap justify-between gap-3"><div><p class="text-sm text-gray-500">Đơn <a class="text-brand-400" href="{{ route('admin.orders.show', $returnRequest->order) }}">{{ $returnRequest->order->order_code }}</a></p><h2 class="mt-1 text-xl font-bold text-white">{{ $returnRequest->reason }}</h2></div><span class="h-fit rounded-full bg-brand-500/15 px-4 py-2 text-xs font-bold text-brand-300">{{ $labels[$returnRequest->status] }}</span></div><p class="mt-4 whitespace-pre-line text-sm leading-6 text-gray-300">{{ $returnRequest->note }}</p>@if($returnRequest->tracking_code)<p class="mt-4 rounded-xl bg-white/5 p-3 text-sm text-gray-300"><strong>Vận đơn:</strong> {{ $returnRequest->shipping_carrier }} · {{ $returnRequest->tracking_code }}</p>@endif</section>
    <section class="rounded-2xl border border-white/5 bg-night-soft p-5"><h2 class="font-bold text-white">Chi tiết tiền hoàn</h2><div class="mt-3 divide-y divide-white/5">@foreach($returnRequest->items as $item)<div class="flex justify-between gap-3 py-3 text-sm"><span class="text-gray-300">{{ $item->orderItem->product_name }} × {{ $item->quantity }}<small class="block text-gray-500">Sau giảm giá + VAT</small></span><strong class="text-white">{{ number_format($item->refund_amount, 0, ',', '.') }}₫</strong></div>@endforeach</div><dl class="space-y-2 border-t border-white/10 py-3 text-sm text-gray-300"><div class="flex justify-between"><dt>Hoàn phí giao ban đầu</dt><dd>{{ number_format($returnRequest->original_shipping_refund, 0, ',', '.') }}₫</dd></div><div class="flex justify-between"><dt>NovaPhone chịu phí gửi trả</dt><dd>{{ number_format($returnRequest->return_shipping_fee, 0, ',', '.') }}₫</dd></div></dl><div class="flex justify-between border-t border-white/10 pt-4"><strong class="text-white">Tổng hoàn</strong><strong class="text-brand-400">{{ number_format($returnRequest->items->sum('refund_amount') + $returnRequest->original_shipping_refund + $returnRequest->return_shipping_fee, 0, ',', '.') }}₫</strong></div></section>
    <section class="rounded-2xl border border-white/5 bg-night-soft p-5"><h2 class="font-bold text-white">Bằng chứng</h2><div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">@foreach($returnRequest->media as $media)<a href="{{ asset('storage/' . $media->path) }}" target="_blank" class="overflow-hidden rounded-xl bg-black">@if($media->media_type === 'video')<video src="{{ asset('storage/' . $media->path) }}" controls class="aspect-square w-full object-cover"></video>@else<img src="{{ asset('storage/' . $media->path) }}" class="aspect-square w-full object-cover">@endif</a>@endforeach</div></section>
</div>
<aside class="space-y-5">
    <section class="rounded-2xl border border-white/5 bg-night-soft p-5"><h2 class="font-bold text-white">Xử lý yêu cầu</h2>
        @if($returnRequest->status === 'return_shipping')<form method="POST" action="{{ route('admin.returns.receive', $returnRequest) }}" class="mt-4">@csrf @method('PATCH')<button class="w-full rounded-xl bg-cyan-600 px-4 py-3 font-semibold text-white">Xác nhận đã nhận kiện hàng</button></form>
        @elseif($returnRequest->status === 'store_received')<form method="POST" action="{{ route('admin.returns.review', $returnRequest) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<textarea name="admin_note" required rows="4" placeholder="Kết quả kiểm tra sản phẩm..." class="w-full rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-white"></textarea><label class="block text-xs font-semibold text-gray-400">Phí khách gửi trả được NovaPhone hoàn lại<input type="text" inputmode="numeric" name="return_shipping_fee" value="{{ old('return_shipping_fee', '0') }}" data-currency-input class="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm text-white" placeholder="Ví dụ: 20.560.650"></label><div class="grid grid-cols-2 gap-2"><button name="decision" value="rejected" class="rounded-xl bg-red-500/20 px-3 py-3 font-semibold text-red-300">Từ chối</button><button name="decision" value="approved" class="rounded-xl bg-emerald-600 px-3 py-3 font-semibold text-white">Duyệt hoàn</button></div></form>
        @elseif($returnRequest->status === 'approved')<form method="POST" action="{{ route('admin.returns.refund', $returnRequest) }}" class="mt-4 space-y-3">@csrf @method('PATCH')@if($returnRequest->order->payment_method === 'cod')<div class="rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-gray-300"><strong class="text-white">Chuyển khoản tới</strong><p class="mt-2">{{ $returnRequest->refund_bank_name }} · {{ $returnRequest->refund_bank_account }}</p><p>{{ $returnRequest->refund_account_name }}</p></div><input name="refund_reference" required placeholder="Mã giao dịch chuyển khoản" class="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm text-white">@else<div class="rounded-xl border border-blue-500/20 bg-blue-500/10 p-3 text-sm leading-6 text-blue-200">Hệ thống sẽ gọi API VNPay và hoàn về giao dịch thanh toán gốc. Phiếu chỉ đóng khi VNPay xác nhận thành công.</div>@endif<button class="w-full rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white" onclick="return confirm('Xác nhận thực hiện hoàn tiền, tạo hóa đơn và gửi email cho khách?');">{{ $returnRequest->order->payment_method === 'vnpay' ? 'Hoàn tiền qua VNPay' : 'Xác nhận đã chuyển khoản' }}</button></form>
        @elseif($returnRequest->status === 'refund_processing')<div class="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-sm leading-6 text-amber-200">VNPay đã tiếp nhận yêu cầu. Hệ thống tự kiểm tra tối đa mỗi {{ config('services.vnpay.refund_query_interval_minutes', 15) }} phút để tránh mã lỗi 94; sau {{ config('services.vnpay.refund_review_after_hours', 24) }} giờ chưa có kết quả sẽ chuyển sang đối soát thủ công.<p class="mt-1">Lần kiểm tra cuối: {{ $returnRequest->last_refund_checked_at?->format('d/m/Y H:i:s') ?: 'Chưa kiểm tra' }}.</p></div><form method="POST" action="{{ route('admin.returns.refund', $returnRequest) }}" class="mt-3">@csrf @method('PATCH')<button class="w-full rounded-xl bg-amber-600 px-4 py-3 font-semibold text-white">Kiểm tra trạng thái VNPay</button></form>
        @elseif($returnRequest->status === 'refund_review_required')<div class="mt-4 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm leading-6 text-red-200"><strong>Cần đối soát thủ công trên VNPay Merchant Portal.</strong><p class="mt-1">{{ $returnRequest->refund_failure_reason }}</p><p class="mt-1">Đã kiểm tra {{ $returnRequest->refund_check_attempts }} lần. Lần cuối: {{ $returnRequest->last_refund_checked_at?->format('d/m/Y H:i') ?: '—' }}.</p></div><form method="POST" action="{{ route('admin.returns.refund', $returnRequest) }}" class="mt-3">@csrf @method('PATCH')<button class="w-full rounded-xl bg-red-600 px-4 py-3 font-semibold text-white">Kiểm tra lại sau đối soát</button></form>
        @elseif($returnRequest->status === 'refund_failed')<div class="mt-4 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm leading-6 text-red-200"><strong>VNPay đã từ chối hoàn tiền.</strong><p class="mt-1">{{ $returnRequest->refund_failure_reason }}</p></div>
        @else<p class="mt-4 text-sm leading-6 text-gray-400">Không có thao tác tiếp theo cho trạng thái này.</p>@endif
    </section>
    <section class="rounded-2xl border border-white/5 bg-night-soft p-5 text-sm"><h2 class="font-bold text-white">Khách hàng</h2><p class="mt-3 text-gray-300">{{ $returnRequest->user->name }}</p><p class="mt-1 text-gray-500">{{ $returnRequest->user->email }}</p>@if($returnRequest->status === 'completed')<a href="{{ route('returns.receipt', $returnRequest) }}" target="_blank" class="mt-4 inline-flex rounded-xl bg-white/10 px-4 py-2 font-semibold text-white">In hóa đơn hoàn tiền</a>@endif @if($returnRequest->admin_note)<div class="mt-4 border-t border-white/5 pt-4 text-gray-400"><strong>Ghi chú duyệt:</strong><p class="mt-1">{{ $returnRequest->admin_note }}</p></div>@endif</section>
</aside></div>
@push('scripts')
<script>
    document.querySelectorAll('[data-currency-input]').forEach((input) => {
        const formatCurrency = () => {
            const digits = input.value.replace(/\D/g, '');
            input.value = digits ? new Intl.NumberFormat('vi-VN').format(Number(digits)) : '';
        };
        input.addEventListener('input', formatCurrency);
        formatCurrency();
    });
</script>
@endpush
@endsection
