<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><title>Hóa đơn hoàn tiền {{ $returnRequest->return_code }}</title>
<style>body{font-family:DejaVu Sans,sans-serif;color:#222;font-size:12px;margin:36px}.head{border-bottom:2px solid #111;padding-bottom:18px;margin-bottom:22px}.brand{font-size:24px;font-weight:bold}.muted{color:#666}.row{display:table;width:100%;margin:8px 0}.row span{display:table-cell}.right{text-align:right}.box{border:1px solid #ddd;padding:16px;margin:18px 0}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #ddd;padding:10px 5px;text-align:left}th:last-child,td:last-child{text-align:right}.total{font-size:16px;font-weight:bold}.footer{margin-top:35px;text-align:center;color:#666}</style></head>
<body><div class="head"><div class="brand">NovaPhone</div><div class="muted">PHIẾU XÁC NHẬN HOÀN TIỀN</div></div>
<div class="row"><span>Mã phiếu: <strong>{{ $returnRequest->return_code }}</strong></span><span class="right">Ngày hoàn: {{ $returnRequest->refunded_at?->format('d/m/Y H:i') }}</span></div>
<div class="row"><span>Đơn hàng: {{ $returnRequest->order->order_code }}</span><span class="right">Khách hàng: {{ $returnRequest->user->name }}</span></div>
<table><thead><tr><th>Sản phẩm</th><th>SL</th><th>Tiền hoàn</th></tr></thead><tbody>@foreach($returnRequest->items as $item)<tr><td>{{ $item->orderItem->product_name }} {{ $item->orderItem->variant_name }}</td><td>{{ $item->quantity }}</td><td>{{ number_format($item->refund_amount, 0, ',', '.') }}₫</td></tr>@endforeach<tr><td colspan="2">Phí giao ban đầu được hoàn</td><td>{{ number_format($returnRequest->original_shipping_refund, 0, ',', '.') }}₫</td></tr><tr><td colspan="2">Phí gửi trả được hoàn</td><td>{{ number_format($returnRequest->return_shipping_fee, 0, ',', '.') }}₫</td></tr><tr class="total"><td colspan="2">TỔNG HOÀN</td><td>{{ number_format($returnRequest->refund_amount, 0, ',', '.') }}₫</td></tr></tbody></table>
<div class="box"><strong>Nơi nhận tiền</strong><br>@if($returnRequest->refund_method === 'vnpay')Hoàn về phương thức/tài khoản VNPay đã thanh toán ban đầu.@else{{ $returnRequest->refund_bank_name }} — {{ $returnRequest->refund_bank_account }}<br>Chủ tài khoản: {{ $returnRequest->refund_account_name }}@endif<br>Mã giao dịch: {{ $returnRequest->refund_reference }}</div>
<div class="footer">Phiếu được tạo tự động bởi NovaPhone và là căn cứ xác nhận giao dịch hoàn tiền.</div></body></html>
